name: "test workflow"

on: 
  push:
    # types: [created, published]
    branches:
      - main
    tags:
      - tests

jobs:
  test_job:
    name: Test Job
    runs-on: macos-latest

    permissions:
      issues: write
      pull-requests: write
    
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
      output4: ${{ steps.step4.outputs.test }}
      output5: ${{ steps.step5.outputs.test }}
    
    steps:
      - id: step1
        run: echo "Hello, World! This is first step."
      - id: step2
        run: pwd
      - id: step3
        run: javac ./Main.java
      - id: step4
        run: java ./Main
      - id: step5
        run: python ./main.py